### ISSUE TITLE
Small typo in the doc

### ISSUE THREAD

**Issue by FredM67** [openenergymonitor/emontx4#16]
Instead "Output AC voltage signal on RJ11 @ 240V = (120V / 60k 0.1%) x 75R 0.1% = 300 mV"

it should be "Output AC voltage signal on RJ11 @ 240V = (**240V** / 60k 0.1%) x 75R 0.1% = 300 mV"

240 instead of 120 ;-)

**Comment by glynhudson** [comment]
Where in the doc is this?  The docs are in this repo

**Comment by FredM67** [comment]
In the file "voltage_sensors.md". The typo is twice in the file.

**Comment by TrystanLea** [comment]
Thanks fixed
