### ISSUE TITLE
EmonLibCM is configured for a maximum of 5 current channels

### ISSUE THREAD

**Issue by brandon3055** [openenergymonitor/emontx4#3]
Just a heads up. I spent a while trying to figure out why manually compiling would result in wired, broken behaviour. 
Turns out this was why.
https://github.com/openenergymonitor/EmonLibCM/blob/avrdb/emonLibCM.cpp#L78
My guess is whoever built the firmware changed this to 6 but then forgot to commit that change.

**Comment by glynhudson** [comment]
Correct, the changes required for emonTx V4 have not yet been pushed. @TrystanLea is working on this and will commit when ready

**Comment by brandon3055** [comment]
Do you know if it would be at all possible to get my hands on a pre-release version of emonlib? It turns out the avrdb branch is a lot more broken than I thought and I have not been able to figure out what's wrong. 

~~Failing that is there any way to configure ical values via serial with the current pre-compiled firmware?~~
Never mind. I found the config menu

**Comment by TrystanLea** [comment]
I've just pushed up the latest version supporting all 6 channels

**Comment by brandon3055** [comment]
Ok so i was confused there for a minute because that's pretty much what I already tried. Turns out the power monitoring is actually working as expected but the current values returned by `EmonLibCM_getIrms(EmonLibCM_getLogicalChannel(x))` are broken.

Edit: I figured it out. Just needed to change that call to `EmonLibCM_getIrms(x)` and it seems to be working now.
