### ISSUE TITLE
Fuses and bootloader

### ISSUE THREAD

**Issue by damiano94** [openenergymonitor/emontx4#7]
Hi,
I didn't found this information in documentation, what are values of fuse bits? And what boot loader is used, opti boot?

Side question, when can we expect 3phase firmware? I don't have 3 phase devices, only single phase devices on different phases, do I really need new firmware or can I just measure power on every phase and add it together to get total consumption?

**Comment by Adminius** [comment]
@damiano94 did you found it out?

https://github.com/SpenceKonde/DxCore/blob/master/PlatformIO.md

**Comment by TrystanLea** [comment]
Hello @damiano94 did you see the new firmware, latest available here https://github.com/openenergymonitor/avrdb_firmware/
1-phase, 3-phase, 6CT & 12CT variants, common base firmware for emonTx4, emonTx5 and emonPi2.
Cheers!
